language: node_js

node_js:
 - "node"

cache:
  directories:
    - node_modules

sudo: false

env:
  - export TWITTER_CONSUMER_KEY='dummy' TWITTER_CONSUMER_SECRET='dummy' TWITTER_ACCESS_TOKEN_KEY='dummy' TWITTER_ACCESS_TOKEN_SECRET='dummy'
