language: node_js

node_js:
 - "node"

cache:
  directories:
    - node_modules

sudo: false

env:
  - export TWITTER_CONSUMER_KEY='dummy' TWITTER_CONSUMER_SECRET='dummy' TWITTER_ACCESS_TOKEN_KEY='dummy' TWITTER_ACCESS_TOKEN_SECRET='dummy' TWITTER_AZ_CONSUMER_KEY='dummy' TWITTER_AZ_CONSUMER_SECRET='dummy' TWITTER_AZ_ACCESS_TOKEN_KEY='dummy' TWITTER_AZ_ACCESS_TOKEN_SECRET='dummy' TWITTER_EU_CONSUMER_KEY='dummy' TWITTER_EU_CONSUMER_SECRET='dummy' TWITTER_EU_ACCESS_TOKEN_KEY='dummy' TWITTER_EU_ACCESS_TOKEN_SECRET='dummy' TWITTER_DRE_CONSUMER_KEY='dummy' TWITTER_DRE_CONSUMER_SECRET='dummy' TWITTER_DRE_ACCESS_TOKEN_KEY='dummy' TWITTER_DRE_ACCESS_TOKEN_SECRET='dummy'

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
